### ISSUE TITLE
Search + Navigation – Prototype

### ISSUE THREAD

**Issue by colinmurphy01** [18F/dtmo-ei#68]
## Story + Context
As a ```traveler``` I want to ```quickly find information, policy + DTS guidance``` in order to ```plan out my trip```.

## Use Cases
- [ ] Constructed Travel
- [ ] Travel Planning Basics
- [ ] Travel Setup Basics
- [ ] Emergency – Flight Cancelled
- [ ] Emergency – GTCC

## Success Criteria
- As a user I'm able easily to navigate to a detail page via a global nav
- As a user I'm able to search for a detail page
- As a user I'm able to share this page with someone else
- As a user I'm able to understand where I am on the site
