### ISSUE TITLE
DTMO Site Content – Prototype

### ISSUE THREAD

**Issue by colinmurphy01** [18F/dtmo-ei#69]
## Story + Context
As a ```traveler``` I want to ```review clear information, policy + DTS guidance``` in order to ```plan out my trip```.

## Use Cases
- [ ] Constructed Travel
- [ ] Travel Planning Basics
- [ ] Travel Setup Basics
- [ ] Emergency – Flight Cancelled
- [ ] Emergency – GTCC

## Success Criteria
- As a user I'm able easily to scan the content page
- As a user I'm able to see a clear/consistent structure for content types
